### ISSUE TITLE
Does not work with cucumber 3+

### ISSUE THREAD

**Issue by kratob** [makandra/cucumber_factory#25] opened 2017-12-05 13:14 UTC
Fails with `cannot load such file -- cucumber/rb_support/rb_language`. `cucumber_priorty` has the same issue and would need to be fixed as well.

We have tests against cucumber `3.0.0.pre.1` which work, but apparently, they broke before the full release.

**Comment by irmela** [comment] 2018-01-11 17:00
Instead of `require 'cucumber/rb_support/rb_language'` you could do `require 'cucumber/glue/registry_and_more'`. 

But this leads to other exceptions that are caused by changes that where made with cucumber 3:

`Transform` got removed and `ParameterType` got introduced. See: https://cucumber.io/blog/2017/09/21/upgrading-to-cucumber-3

This is why `world.Transform(value)` throws a `NoMethodError` exception.

**Comment by triskweline** [comment] 2018-01-11 17:20
I read the cucumber.io post. I don't quite understand the point of introducing `ParamaterType`. What's the difference to `Transform`?

**Comment by denzelem** [comment] 2018-04-04 07:44
Support for Cucumber 3.0 and 3.1 was added in  `v1.12.0` https://github.com/makandra/cucumber_factory/commit/10ee48875b3d90523e7dd1383bdc3f93622b20f7, I will close this issue.

**Closed by denzelem** 2018-04-04 07:44 UTC
Labels: Bug
